### ISSUE TITLE
Publish destroy messages for models removed via cascade delete.

### ISSUE THREAD

**Issue by werwty** [RedHatInsights/sources-api#179]
Currently there are three ways of removing an Authentication: 
  - making a DELETE API call directly to Authentication
  - deleting the Authentication's parent Source
  - deleting the Authentication's parent Endpoint

For the first method, a `Authentication.destroy` event is put into Kafka. For the second only a `Source.destroy` event is raised. And for the third only an `Endpoint.destroy` event is raised

This means anyone who wants to be notified when a specific Authentication is removed has to listen to three event_types. They would also have to keep track of the source_id,  endpoint_id, and authentication_id of the platform object.

Instead, if Sources raised an `Authentication.destroy` message even in the case of an authentication being cascading deleted because its parent was removed, it would do much to simplify the necessary workflow.

Note that I'm not advocating a event be fired for delete in all the tables, as there are many intermediate join tables that users don't care just. I think the event should be fired just in the case of the user facing objects that an cascade delete can affect (Authentication, Endpoint).

**Comment by agrare** [comment]
:+1: this make sense and would be a good enhancement

**Comment by werwty** [comment]
It looks like sources now does generate messages for most cascade deleted objects. 
However I still do not see a cascaded delete message for the ApplicationAuthentication object. Can this be fixed?

**Comment by slemrmartin** [comment]
https://issues.redhat.com/browse/RHCLOUD-10263 ^^^
