### ISSUE TITLE
Creating 2+ applications and 2+ authentications can lead to ambiguity.

### ISSUE THREAD

**Issue by werwty** [RedHatInsights/sources-api#182]
The UI disallows the creation of multiple authentications of the same type. But this is doable via the API.

Steps to reproduce:
```
## Create a Source
http -a insights-qa POST https://ci.cloud.redhat.com/api/sources/v1.0/sources name=cloudmeter-demo source_type_id=2

## Create an Endpoint
http -a insights-qa POST https://ci.cloud.redhat.com/api/sources/v1.0/endpoints role=aws default=true source_id=1575


## Create two Application
http -a insights-qa POST https://ci.cloud.redhat.com/api/sources/v1.0/applications application_type_id=5 source_id=1575
http -a insights-qa POST https://ci.cloud.redhat.com/api/sources/v1.0/applications application_type_id=5 source_id=1575

## Create two Authentications
http -a insights-qa POST https://ci.cloud.redhat.com/api/sources/v1.0/authentications authtype=cloud-meter-arn password=arn:aws:iam::114204391493:role/cloudigrade-ci-role resource_type=Endpoint resource_id=1093

http -a insights-qa POST https://ci.cloud.redhat.com/api/sources/v1.0/authentications authtype=cloud-meter-arn password=arn:aws:iam::114204391493:role/cloudigrade-ci-role-2 resource_type=Endpoint resource_id=1093

```

There is no way of figuring out which Authentication belongs to which Application. This ambiguity is problematic when we try to figure out whether an authentication should be deleted when a 'cloud-meter` application is deleted.

**Comment by agrare** [comment]
Hey @werwty the addition of the cloud meter auth type was a stopgap until we got a hard link between the app and the auth.  I started that work here https://github.com/RedHatInsights/sources-api/pull/184 but for now using the authtype is the best we have.

**Comment by werwty** [comment]
:+1: Good to know! I didn't know that was in progress. Thanks @agrare !

**Comment by slemrmartin** [comment]
done
