### ISSUE TITLE
As a user I want Sources to support a shared ARN authentication between different applications

### ISSUE THREAD

**Issue by werwty** [RedHatInsights/sources-api#183]
This is probably a future enhancement.

As things are now, when an Authentication is created it's type `arn` for cost management, and `cloud-meter-arn` for Cloud Meter. It is very possible that a user would have a singular ARN that has the policy configured to support but Cost Management and Cloud Meter. 

I would expect an ARN authentication to be application agnostic. But for there to be some foreign key relationship typing an ARN to specific Applications. That way an ARN can belong to Cost Management, Cloud Meter, both, or some other future application with ARN support.

**Comment by agrare** [comment]
Okay backend for this is merged, now we just need the UI to start setting this when configuring the source.

Going to assign this to @rvsia for now

**Comment by rvsia** [comment]
Not sure, what I am supposed to do. Just to add another API call (create authapp) when creating a source with an application?

However, there are more UI concerns I have. If it's possible to have multiple authentication of the same type, then we need to add some authentication management to Sources UI.

Users should be able to
- remove authentication from application and use different one
- add a new authentication, not assigned to an app (?)
- choose an existing authentication or create a new authentication when attaching an app to an existing source
- see which applications are using an authentication when editing the authentication (in the edit form)

**Comment by agrare** [comment]
@rvsia I believe that is what they are asking for (unless @werwty intends to do this all from the API).  We should start with at a minimum creating this link when we create an authentication record the way we do today so that it can be looked up more efficiently and then we'll need UX input on designing an authentication manager
