### ISSUE TITLE
Add last_checked_at and last_available_at to endpoints/sources/applications

### ISSUE THREAD

**Issue by agrare** [RedHatInsights/sources-api#206]
It would be beneficial if we store the last time a resource (endpoint, source, application, authentication) was checked and when it was last available.

We can add timestamp columns to track this to any resource that has an availability_status attribute

**Comment by iphands** [comment]
+1

Remediations is looking to use the availability check to drive their pre-flight check page.

Remediations would need to be able to POST to check_availability then poll until it sees the last_available timestamp change in in order to know the check was completed.

**Comment by Fryguy** [comment]
> POST to check_availability then poll

In this case, you would not need to poll, as when the availability check completes, it would modify the last_checked_at column, which in turn will raise a kafka event.  So, you would just watch kafka for the event.

**Comment by jharting** [comment]
@Fryguy in the scenario that @iphands describes the API is consumed by a react app directly. There polling seems to be the most straightforward approach.

**Comment by iphands** [comment]
Thanks @jharting, and thanks @Fryguy in the future when we do have a websocket connection to Remediations API it would be good to consume the message and kill the polling though.

**Comment by syncrou** [comment]
@agrare @gtanzillo when we discussed this it seemed like we could get passed a good deal of the requirements by simply adding the columns and exposing them via the open api spec.  I'm all for that as a middle ground to keep this moving forward.

**Comment by syncrou** [comment]
cc - @lphiri @iphands https://github.com/RedHatInsights/sources-api/issues/206#issuecomment-622492889

**Comment by iphands** [comment]
@syncrou hey any update here? The receptor controller team is blocked on this one.

**Comment by slemrmartin** [comment]
done
