### ISSUE TITLE
Broken availability_checks via Kafka

### ISSUE THREAD

**Issue by pkomanek** [RedHatInsights/sources-api#286]
We've just found that there is an issue in processing the availability_status event incoming from the Kafka. It makes the listener to skip update for `Applications`, `Endpoints` and `Sources`.  This issue is based on the https://issues.redhat.com/browse/RHCLOUD-10879.

Changes:
 - [x] [producer_fix](https://github.com/RedHatInsights/topological_inventory-providers-common/pull/68)
 - [x] [receiver_fix](https://github.com/RedHatInsights/sources-api/pull/285)

**Comment by slemrmartin** [comment]
all PRs merged, closing
