### ISSUE TITLE
Models interactions with availability_status

### ISSUE THREAD

**Issue by pkomanek** [RedHatInsights/sources-api#317]
# Description
This issue is focused on sources-api models interactions and handling their availability_status (`Authentication`, `Application`, `Endpoint`, `Source`). We recently added the availability_concern, which removes the availability_status from model after any attribute change(except the IGNORE_LIST*). 
```
  IGNORE_LIST = [
    "availability_status",
    "availability_status_error",
    "last_available_at",
    "last_checked_at",
    "updated_at",
    "name"
  ].freeze
```
We also wanna add some interactions between models. So for example clearing the status from `Endpoint` should force related `Source` to do the same. We also consider to call for availability check after setting the `Source` status to `nil`.

 # Models relations
![relations_state](https://user-images.githubusercontent.com/19405716/107619957-3eb47a80-6c54-11eb-8c72-c492e96cd6ee.jpeg)

# Models interactions(attribute changed)
![status_change](https://user-images.githubusercontent.com/19405716/107622771-981ea880-6c58-11eb-9a7d-0605efbac117.jpg)

@lindgrenj6 @slemrmartin What do you think about these interactions? Also do we want to add a call for the `#availability_check` after updating the status on `Source`(only if status is `nil`)? And What about removing the Models? For example from my point of view removing the `Endpoint` should also force the same interaction as the status_change.

Based on these Jira tickets:
* https://issues.redhat.com/browse/RHCLOUD-11681
* https://issues.redhat.com/browse/RHCLOUD-11552
* https://issues.redhat.com/browse/RHCLOUD-10278

**Comment by pkomanek** [comment]
I would like to split this into three different issues:

1) Interactions between models(after status change to nil)
    * Auth:
         - reset realted source status
         - reset related endpoint status
         - reset status for all related applications
     * Endpoint:
         - reset realted source status
     * App:
         - reset realted source status(only if there is no related endpoint)
2) Request new availability check after Source status is set to nil
3) Modify the availability status check logic to aggregate the status from all related models
    * for example I think that right now if there is no related endpoint, we just check the first app status.

What do you think @lindgrenj6 and @slemrmartin?

**Comment by slemrmartin** [comment]
- At first we should consider if the availability status for Authentication makes sense. I don't see any usage so we could remove these columns
- Other interactions looks good to me
- Deleting of the Endpoint/App/Auth should reset Source's status
- And yes, reset Source#availability_status to `nil` should invoke availability check immediatelly. 

Anyway, the Authentication's availability status is never set, so changing other columns can't change it's status => can't invoke the reset in other models. So the model interactions has to be triggered by the other values change, not by availability_status change to nil

**Comment by pkomanek** [comment]
@slemrmartin based on this comment https://github.com/RedHatInsights/sources-api/pull/325#issuecomment-786131947 we will keep the `availability_status` logic in the `Authentication` model.

**Comment by pkomanek** [comment]
Based on this comment https://github.com/RedHatInsights/sources-api/pull/325#issuecomment-786131947 we will keep the `availability_status` logic in the `Authentication` model. We also remove the `status` and `status_details` columns.

Here is list of all related PRs:
 * https://github.com/RedHatInsights/sources-api/pull/316
 * https://github.com/RedHatInsights/sources-api/pull/323
 * https://github.com/RedHatInsights/sources-api/pull/325

**Comment by slemrmartin** [comment]
Refactoring...

![Sources availability-status](https://user-images.githubusercontent.com/1814995/114379045-a1f55700-9b88-11eb-8b1d-e34f2c98dea2.png)

**Comment by slemrmartin** [comment]
done

**Comment by slemrmartin** [comment]
not done :) destroy is missing
